---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-appbundle
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: The app bundle POC project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appbundle
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/tostieme/myargo.git
      revision: HEAD
      directories:
      - path: applications/*
      - path: applications/_appset
        exclude: true
      template:
        metadata: {}
        spec:
          project: my-appbundle
          source:
            repoURL: https://github.com/tostieme/myargo.git
          destination:
            server: https://kubernetes.default.svc
  - git:
      repoURL: https://github.com/tostieme/myargo.git
      revision: HEAD
      directories:
      - path: applications/_appset
      template:
        metadata:
          name: applications-appset
        spec:
          project: my-appbundle
          source:
            repoURL: https://github.com/tostieme/myargo.git
          destination:
            server: https://kubernetes.default.svc
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: my-appbundle
      source:
        repoURL: https://github.com/tostieme/myargo.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
