apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmCharts:
- name: trust-manager
  version: 0.5.0
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  namespace: cert-manager
  releaseName: cert-manager-trust