apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx

resources:
  - namespace.yaml

helmCharts:
- name: nginx
  version: 15.1.5
  repo: https://charts.bitnami.com/bitnami
  valuesFile: values.yaml
  namespace: nginx
  releaseName: nginx