apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - namespace.yaml

helmCharts:
- name: vault
  version: 0.25.0
  repo: https://helm.releases.hashicorp.com
  valuesFile: values.yaml
  namespace: vault
  releaseName: vault