apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd

resources:
  - namespace.yaml
  - cert-manager-identity-issuer.yaml
  - cert-manager-ca-issuer.yaml
  - ca-bundle.yaml

helmCharts:
- name: linkerd-crds
  version: 1.8.0
  repo: https://helm.linkerd.io/stable
  valuesFile: values-linkerd-crds.yaml
  namespace: linkerd
  releaseName: linkerd-crds
- name: linkerd-control-plane
  version: 1.16.2
  repo: https://helm.linkerd.io/stable
  valuesFile: values-linkerd-control-plane.yaml
  namespace: linkerd
  releaseName: linkerd-control-plane