apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml

helmCharts:
- name: argo-cd
  version: 5.41.2
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  namespace: argocd
  releaseName: argocd